match_schemas:
  description: >
    Analyze the retrieved data and match schemas.
    Query: {query}
    Database Data: {db_data}
    Web Data: {web_data}  
    Document Data: {doc_data}
  expected_output: >
    Matched schemas and relationships between different data sources.
  agent: schema_matcher  