generate_sql:
  description: >
    Generate SQL query based on the analyzed requirements and schema matches.
    Query: {query}
    Schema matches: {schema_matches}
  expected_output: >
    A valid SQL query that retrieves the requested information.
  agent: sql_generator_agent  